config/routes.rb
Rails.application.routes.draw do
  resources :ingressos

  resources :loteingressos

  get 'home/index'
  root :to => "home#index"

  resources :eventos

  resources :clientes

  resources :ambientes

  resources :empresas

end

app/models/ambiente.rb
class Ambiente < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  belongs_to :empresa
  belongs_to :ambiente
end

app/models/ingresso.rb
class Ingresso < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :loteingresso
end

app/models/loteingresso.rb
class Loteingresso < ActiveRecord::Base
  belongs_to :evento
end

app/controllers/ambientes_controller.rb
class AmbientesController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:ambiente, {}).permit( :nome, :capacidade, :endereco, :complemento,
                      :numero, :bairro, :cidade, :estado, :cep)]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:cliente, {}).permit( :nome, :data_nascimento, :cpf, :email, :senha)]
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < InheritedResources::Base
    def build_resource_params
        [params.fetch(:empresa, {}).permit( :cnpj,:nome, :endereco, :complemento,
                      :numero, :bairro, :cidade, :estado, :cep)]
    end
end

app/controllers/eventos_controller.rb
class EventosController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:evento, {}).permit( :nome, :categoria,:data, :hora, :empresa_id,
                      :ambiente_id, :descricao)]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingressos_controller.rb
class IngressosController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:ingresso, {}).permit(:cadeira_numerada, :area ,:cliente_id, :loteingresso_id)]
    end
end

app/controllers/loteingressos_controller.rb
class LoteingressosController < InheritedResources::Base
	def build_resource_params
        [params.fetch(:loteingresso, {}).permit(:numero_lote, :preco ,:quantidade, :evento_id)]
    end
end

app/helpers/ambientes_helper.rb
module AmbientesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingressos_helper.rb
module IngressosHelper
end

app/helpers/loteingressos_helper.rb
module LoteingressosHelper
end

app/views/ambientes/_form.html.haml
= simple_form_for @ambiente, html: { class: "form-horizontal"}, defaults: { input_html: { class: 'form-control' } } do |f|
  = f.error_notification
  .form-group.form-inputs
    .col-lg-6
      = f.input :nome
      = f.input :capacidade
      = f.input :endereco , label: 'Endereço'
      = f.input :complemento
      = f.input :numero , label: 'Número'
      = f.input :bairro
      = f.input :cidade
      = f.input :estado
      = f.input :cep , label: 'CEP'

  .form-group.form-actions
    .col-lg-10.col-lg-offset-2
      = f.button :submit, 'Salvar', :class => "btn btn-success"

app/views/ambientes/edit.html.haml
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-map-marker.fa-5x
      .col-xs-9.text-right
        %h1 Editing ambiente
  .panel-body

    = render 'form'

    = link_to 'Show', @ambiente, class: 'btn btn-info'
    \|
    = link_to 'Back', ambientes_path, class: 'btn btn-default'

app/views/ambientes/index.html.haml
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-map-marker.fa-5x
      .col-xs-9.text-right
        %h1 Listing ambientes
  .panel-body
    %table.table.table-hover
      %tr
        %th Nome
        %th Capacidade
        %th Endereco
        %th Complemento
        %th Numero
        %th Bairro
        %th Cidade
        %th Estado
        %th Cep
        %th{:colspan => 3} Ações

      - @ambientes.each do |ambiente|
        %tr
          %td= ambiente.nome
          %td= ambiente.capacidade
          %td= ambiente.endereco
          %td= ambiente.complemento
          %td= ambiente.numero
          %td= ambiente.bairro
          %td= ambiente.cidade
          %td= ambiente.estado
          %td= ambiente.cep
          %td
            = link_to 'Show', ambiente, class: 'btn btn-success'
            = link_to 'Edit', edit_ambiente_path(ambiente), class: 'btn btn-primary'
            = link_to 'Excluir', ambiente, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %br

    = link_to 'New Ambiente', new_ambiente_path, class: 'btn btn-success'

app/views/ambientes/new.html.haml
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-map-marker.fa-5x
      .col-xs-9.text-right
        %h1 New ambiente
  .panel-body
    = render 'form'

    = link_to 'Back', ambientes_path, class: 'btn btn-default'

app/views/ambientes/show.html.haml
%p#notice= notice

.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-map-marker.fa-5x
      .col-xs-9.text-right
        %h1 Ambiente cadastrado
  .panel-body
    %table.table.table-hover
      %tr
        %th Nome:
        %td
          = @ambiente.nome
      %tr
        %th Capacidade:
        %td
          = @ambiente.capacidade
      %tr
        %th Endereço:
        %td
          = @ambiente.endereco
      %tr
        %th Complemento:
        %td
          = @ambiente.complemento
      %tr
        %th Número:
        %td
          = @ambiente.numero
      %tr
        %th Bairro:
        %td
          = @ambiente.bairro
      %tr
        %th Cidade:
        %td
          = @ambiente.cidade
      %tr
        %th Estado:
        %td
          = @ambiente.estado
      %tr
        %th CEP:
        %td
          = @ambiente.cep

    = link_to 'Edit', edit_ambiente_path(@ambiente), class: 'btn btn-info'
    \|
    = link_to 'Back', ambientes_path, class: 'btn btn-default'

app/views/clientes/_form.html.haml
= simple_form_for @cliente, html: { class: "form-horizontal"}, defaults: { input_html: { class: 'form-control' } } do |f|
  = f.error_notification
  .form-group.form-inputs
    .col-lg-6
      = f.input :nome
      = f.input :data_nascimento, label: 'Data Nascimento', as: :string
      = f.input :cpf , label: 'CPF'
      = f.input :email
      = f.input :senha, as: :password
  .form-group.form-actions
    .col-lg-10.col-lg-offset-2
      = f.button :submit, 'Salvar', :class => "btn btn-success"

app/views/clientes/edit.html.haml
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-users.fa-5x
      .col-xs-9.text-right
        %h1 Editing cliente
  .panel-body

    = render 'form'

    = link_to 'Show', @cliente, class: 'btn btn-info'
    \|
    = link_to 'Back', clientes_path, class: 'btn btn-default'

app/views/clientes/index.html.haml
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-users.fa-5x
      .col-xs-9.text-right
        %h1 Listing clientes
  .panel-body
    %table.table.table-hover
      %tr
        %th Nome
        %th Data Nascimento
        %th CPF
        %th Email
        %th Senha
        %th{:colspan => 3} Ações

      - @clientes.each do |cliente|
        %tr
          %td= cliente.nome
          %td= cliente.data_nascimento
          %td= cliente.cpf
          %td= cliente.email
          %td= cliente.senha
          %td
            = link_to 'Show', cliente , class: 'btn btn-success'
            = link_to 'Edit', edit_cliente_path(cliente), class: 'btn btn-primary'
            = link_to 'Excluir', cliente, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %br

    = link_to 'New Cliente', new_cliente_path, class: 'btn btn-success'

app/views/clientes/new.html.haml
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-users.fa-5x
      .col-xs-9.text-right
        %h1 New cliente
  .panel-body
    = render 'form'

    = link_to 'Back', clientes_path , class: 'btn btn-default'

app/views/clientes/show.html.haml
%p#notice= notice
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-users.fa-5x
      .col-xs-9.text-right
        %h1 Cliente cadastrado
  .panel-body
    %table.table.table-hover
      %tr
        %th Nome:
        %td
          = @cliente.nome
      %tr
        %th Data Nascimento:
        %td
          = @cliente.data_nascimento
      %tr
        %th CPF:
        %td
          = @cliente.cpf
      %tr
        %th Email:
        %td
          = @cliente.email
      %tr
        %th Senha:
        %td
          = @cliente.senha

    = link_to 'Edit', edit_cliente_path(@cliente), class: 'btn btn-info'
    \|
    = link_to 'Back', clientes_path , class: 'btn btn-default'

app/views/empresas/_form.html.haml
= simple_form_for @empresa, html: { class: "form-horizontal"}, defaults: { input_html: { class: 'form-control' } } do |f|
  = f.error_notification

  .form-group.form-inputs
    .col-lg-6
      = f.input :cnpj , label: 'CNPJ'
      = f.input :nome
      = f.input :endereco , label: 'Endereço'
      = f.input :complemento
      = f.input :numero , label: 'Número'
      = f.input :bairro
      = f.input :cidade
      = f.input :estado
      = f.input :cep , label: 'CEP'

  .form-group.form-actions
    .col-lg-10.col-lg-offset-2
      = f.button :submit, 'Salvar', :class => "btn btn-success"

app/views/empresas/edit.html.haml
.panel.panel-yellow
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tasks.fa-5x
      .col-xs-9.text-right
        %h1 Editing empresa
  .panel-body
    = render 'form'

    = link_to 'Show', @empresa, class: 'btn btn-info'
    \|
    = link_to 'Back', empresas_path, class: 'btn btn-default'

app/views/empresas/index.html.haml
.panel.panel-yellow
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tasks.fa-5x
      .col-xs-9.text-right
        %h1 Listing empresas
  .panel-body
    %table.table.table-hover
      %tr
        %th Cnpj
        %th Nome
        %th Endereco
        %th Complemento
        %th Número
        %th Bairro
        %th Cidade
        %th Estado
        %th Cep
        %th{:colspan => 3} Ações

      - @empresas.each do |empresa|
        %tr
          %td= empresa.cnpj
          %td= empresa.nome
          %td= empresa.endereco
          %td= empresa.complemento
          %td= empresa.numero
          %td= empresa.bairro
          %td= empresa.cidade
          %td= empresa.estado
          %td= empresa.cep
          %td
            = link_to 'Show', empresa,  class: 'btn btn-success'
            = link_to 'Edit', edit_empresa_path(empresa), class: 'btn btn-primary'
            = link_to 'Excluir', empresa, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %br

    = link_to 'New Empresa', new_empresa_path, class: 'btn btn-success'

app/views/empresas/new.html.haml
.panel.panel-yellow
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tasks.fa-5x
      .col-xs-9.text-right
        %h1 New empresa
  .panel-body
    = render 'form'

    = link_to 'Back', empresas_path, class: 'btn btn-default'

app/views/empresas/show.html.haml
%p#notice= notice
.panel.panel-yellow
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tasks.fa-5x
      .col-xs-9.text-right
        %h1 Empresa cadastrado
  .panel-body
    %table.table.table-hover
      %tr
        %th CNPJ:
        %td
          = @empresa.cnpj
      %tr
        %th Nome:
        %td
          = @empresa.nome
      %tr
        %th Endereço:
        %td
          = @empresa.endereco
      %tr
        %th Complemento:
        %td
          = @empresa.complemento
      %tr
        %th Número:
        %td
          = @empresa.numero
      %tr
        %th Bairro:
        %td
          = @empresa.bairro
      %tr
        %th Cidade:
        %td
          = @empresa.cidade
      %tr
        %th Estado:
        %td
          = @empresa.estado
      %tr
        %th CEP:
        %td
          = @empresa.cep

    = link_to 'Edit', edit_empresa_path(@empresa), class: 'btn btn-info'
    \|
    = link_to 'Back', empresas_path, class: 'btn btn-default'

app/views/eventos/_form.html.haml
= simple_form_for @evento, html: { class: "form-horizontal"}, defaults: { input_html: { class: 'form-control' } }  do |f|
  = f.error_notification

  .form-group.form-inputs
    .col-lg-6
      = f.input :nome
      = f.input :categoria
      = f.input :data, as: :string
      = f.input :hora, as: :string
      = f.association :empresa , label_method: :nome
      = f.association :ambiente , label_method: :nome
      = f.input :descricao, label: 'Descrição'

  .form-group.form-actions
    .col-lg-10.col-lg-offset-2
      = f.button :submit, 'Salvar', :class => "btn btn-success"

app/views/eventos/edit.html.haml
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-music.fa-5x
      .col-xs-9.text-right
        %h1 Editing evento
  .panel-body
    = render 'form'

    = link_to 'Show', @evento, class: 'btn btn-info'
    \|
    = link_to 'Back', eventos_path, class: 'btn btn-default'

app/views/eventos/index.html.haml
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-music.fa-5x
      .col-xs-9.text-right
        %h1 Listing eventos
  .panel-body
    %table.table.table-hover
      %tr
        %th Nome
        %th Categoria
        %th Data
        %th Hora
        %th Empresa
        %th Ambiente
        %th Descricao
        %th{:colspan => 3} Ações

      - @eventos.each do |evento|
        %tr
          %td= evento.nome
          %td= evento.categoria
          %td= evento.data
          %td= evento.hora.strftime("%H:%M")
          %td= evento.empresa.nome
          %td= evento.ambiente.nome
          %td= evento.descricao
          %td
            = link_to 'Show', evento, class: 'btn btn-success'
            = link_to 'Edit', edit_evento_path(evento),class: 'btn btn-primary'
            = link_to 'Excluir', evento, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %br

    = link_to 'New Evento', new_evento_path,  class: 'btn btn-success',role: "button"

app/views/eventos/new.html.haml
.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-music.fa-5x
      .col-xs-9.text-right
        %h1 New evento
  .panel-body
    = render 'form'
    = link_to 'Back', eventos_path, class: 'btn btn-default'

app/views/eventos/show.html.haml
%p#notice= notice

.panel.panel-primary
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-music.fa-5x
      .col-xs-9.text-right
        %h1 Evento cadastrado
  .panel-body
    %table.table.table-hover
      %tr
        %th Nome:
        %td
          = @evento.nome
      %tr
        %th Categoria:
        %td
          = @evento.categoria
      %tr
        %th Data:
        %td
          = @evento.data
      %tr
        %th Hora:
        %td
          = @evento.hora.strftime("%H:%M")
      %tr
        %th Empresa:
        %td
          = @evento.empresa.nome
      %tr
        %th Ambiente:
        %td
          = @evento.ambiente.nome
      %tr
        %th Descrição:
        %td
          = @evento.descricao

    = link_to 'Edit', edit_evento_path(@evento), class: 'btn btn-info'
    \|
    = link_to 'Back', eventos_path, class: 'btn btn-default'

app/views/home/index.html.haml
%h1 Venda de Ingressos

.row
  .col-sm-6.col-md-4
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-music.fa-5x
          .col-xs-9.text-right
            %h2 Evento
      .panel-footer
        = link_to 'Eventos', eventos_path, class: 'btn btn-primary'
        = link_to 'New evento', new_evento_path, class: 'btn btn-success'
  .col-sm-6.col-md-4
    .panel.panel-yellow
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-tasks.fa-5x
          .col-xs-9.text-right
            %h2 Empresa
      .panel-footer
        = link_to 'Empresas', empresas_path, class: 'btn btn-primary'
        = link_to 'New empresa', new_empresa_path, class: 'btn btn-success'
  .col-sm-6.col-md-4
    .panel.panel-red
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-map-marker.fa-5x
          .col-xs-9.text-right
            %h2 Ambiente
      .panel-footer
        = link_to 'Ambientes', ambientes_path, class: 'btn btn-primary'
        = link_to 'New ambiente', new_ambiente_path, class: 'btn btn-success'
  .col-sm-6.col-md-4
    .panel.panel-green
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-tags.fa-5x
          .col-xs-9.text-right
            %h2 Lote Ingresso
      .panel-footer
        = link_to 'Lote Ingressos', loteingressos_path, class: 'btn btn-primary'
        = link_to 'New Lote ingressos ', new_loteingresso_path, class: 'btn btn-success'
  .col-sm-6.col-md-4
    .panel.panel-red
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-ticket.fa-5x
          .col-xs-9.text-right
            %h2 Ingresso
      .panel-footer
        = link_to 'Ingressos', ingressos_path, class: 'btn btn-primary'
        = link_to 'New ingressos ', new_ingresso_path, class: 'btn btn-success'
  .col-sm-6.col-md-4
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-users.fa-5x
          .col-xs-9.text-right
            %h2 Cliente
      .panel-footer
        = link_to 'Clientes', clientes_path, class: 'btn btn-primary'
        = link_to 'New Cliente ', new_cliente_path, class: 'btn btn-success'

app/views/ingressos/_form.html.haml
= simple_form_for @ingresso, html: { class: "form-horizontal"}, defaults: { input_html: { class: 'form-control' } } do |f|
  = f.error_notification

  .form-group.form-inputs
    .col-lg-6
      = f.input :cadeira_numerada, label: 'Cadeira Númerada'
      = f.input :area, label: 'Área'
      = f.association :cliente, label_method: :nome
      = f.association :loteingresso, label_method: :numero_lote, label: 'Lote Ingresso'

  .form-group.form-actions
    .col-lg-10.col-lg-offset-2
      = f.button :submit, 'Salvar', :class => "btn btn-success"

app/views/ingressos/edit.html.haml
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-ticket.fa-5x
      .col-xs-9.text-right
        %h1 Editing ingresso
  .panel-body
    = render 'form'

    = link_to 'Show', @ingresso, class: 'btn btn-info'
    \|
    = link_to 'Back', ingressos_path,  class: 'btn btn-default'

app/views/ingressos/index.html.haml
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-ticket.fa-5x
      .col-xs-9.text-right
        %h1 Listing ingressos
  .panel-body
    %table.table.table-hover
      %tr
        %th Cadeira numerada
        %th Area
        %th Cliente
        %th Loteingresso
        %th{:colspan => 3} Ações

      - @ingressos.each do |ingresso|
        %tr
          %td= ingresso.cadeira_numerada
          %td= ingresso.area
          %td= ingresso.cliente.nome
          %td= ingresso.loteingresso.numero_lote
          %td
            = link_to 'Show', ingresso,  class: 'btn btn-success'
            = link_to 'Edit', edit_ingresso_path(ingresso), class: 'btn btn-primary'
            = link_to 'Excluir', ingresso, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %br

    = link_to 'New Ingresso', new_ingresso_path, class: 'btn btn-success'

app/views/ingressos/new.html.haml
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-ticket.fa-5x
      .col-xs-9.text-right
        %h1 New ingresso
  .panel-body
    = render 'form'

    = link_to 'Back', ingressos_path, class: 'btn btn-default'

app/views/ingressos/show.html.haml
%p#notice= notice
.panel.panel-red
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-ticket.fa-5x
      .col-xs-9.text-right
        %h1 Ingresso cadastrado
  .panel-body
    %table.table.table-hover
      %tr
        %th Cadeira Númerada:
        %td
          = @ingresso.cadeira_numerada
      %tr
        %th Área:
        %td
          = @ingresso.area
      %tr
        %th Cliente:
        %td
          = @ingresso.cliente.nome
      %tr
        %th Lote Ingresso:
        %td
          = @ingresso.loteingresso.numero_lote

    = link_to 'Edit', edit_ingresso_path(@ingresso), class: 'btn btn-info'
    \|
    = link_to 'Back', ingressos_path, class: 'btn btn-default'

app/views/loteingressos/_form.html.haml
= simple_form_for @loteingresso, html: { class: "form-horizontal"}, defaults: { input_html: { class: 'form-control' } } do |f|
  = f.error_notification

  .form-group.form-inputs
    .col-lg-6
      = f.input :numero_lote, label: "Número Lote"
      = f.input :preco,  label: "Preço"
      = f.input :quantidade
      = f.association :evento,  label_method: :nome

  .form-group.form-actions
    .col-lg-10.col-lg-offset-2
      = f.button :submit, 'Salvar', :class => "btn btn-success"

app/views/loteingressos/edit.html.haml
.panel.panel-green
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tags.fa-5x
      .col-xs-9.text-right
        %h1 Editing loteingresso
  .panel-body

    = render 'form'

    = link_to 'Show', @loteingresso, class: 'btn btn-info'
    \|
    = link_to 'Back', loteingressos_path, class: 'btn btn-default'

app/views/loteingressos/index.html.haml
.panel.panel-green
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tags.fa-5x
      .col-xs-9.text-right
        %h1 Listing loteingressos
  .panel-body
    %table.table.table-hover
      %tr
        %th Numero lote
        %th Preco
        %th Quantidade
        %th Evento
        %th{:colspan => 3} Ações

      - @loteingressos.each do |loteingresso|
        %tr
          %td= loteingresso.numero_lote
          %td= loteingresso.preco
          %td= loteingresso.quantidade
          %td= loteingresso.evento.nome
          %td
            = link_to 'Show', loteingresso, class: 'btn btn-success'
            = link_to 'Edit', edit_loteingresso_path(loteingresso), class: 'btn btn-primary'
            = link_to 'Excluir', loteingresso, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

    %br

    = link_to 'New Loteingresso', new_loteingresso_path, class: 'btn btn-success'

app/views/loteingressos/new.html.haml
.panel.panel-green
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tags.fa-5x
      .col-xs-9.text-right
        %h1 New loteingresso
  .panel-body
    = render 'form'

    = link_to 'Back', loteingressos_path, class: 'btn btn-default'

app/views/loteingressos/show.html.haml
%p#notice= notice
.panel.panel-green
  .panel-heading
    .row
      .col-xs-3
        %i.fa.fa-tags.fa-5x
      .col-xs-9.text-right
        %h1 Lote Ingresso cadastrado
  .panel-body
    %table.table.table-hover
      %tr
        %th Número Lote:
        %td
          = @loteingresso.numero_lote
      %tr
        %th Preço:
        %td
          = @loteingresso.preco
      %tr
        %th Quantidade:
        %td
          = @loteingresso.quantidade
      %tr
        %th Evento:
        %td
          = @loteingresso.evento.nome

    = link_to 'Edit', edit_loteingresso_path(@loteingresso), class: 'btn btn-info'
    \|
    = link_to 'Back', loteingressos_path, class: 'btn btn-default'